#Requires AutoHotkey v2.0

; AUTO-GENERATED - DO NOT EDIT
; timestamp 20251210170437
; generated by OneLocale_Baker.ahk :: BakeLangMap()
; source = E:\Programs\AHK_root\AHKv2A\OneLocale\utilities\OneLocale_Demo\lang_load\OneLocale_Demo-[de].lang

OneLocale_BuildMap_de()

/*****************************************
 * ##### OneLocale_BuildMap_de: initialize global Map 'g_lang_map'
 * - Conversion of a .LANG file into a Map tree
 */
OneLocale_BuildMap_de()
{
    global g_lang_map
    if (!IsObject(g_lang_map))
        g_lang_map := Map()

    local mlng, msec, msub, asec
    mlng := Map()
    mlng[":lang_id:"] := "de"
    g_lang_map["de"] := mlng


    ; section ':extenders:'
    msec := Map()
    msec[":map_name:"] := ":extenders:"
    mlng[":extenders:"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("..\..\..\lib\OneLocale_Dialog-template.lang")
    asec.Push("..\..\..\lib\Versions-template.lang")
    msec["[section]"] := asec

    ; ...section keys and values


    ; section 'General'
    msec := Map()
    msec[":map_name:"] := "General"
    mlng["General"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("version     = 1.4")
    asec.Push("lang_id     = de")
    asec.Push("lang_name   = German")
    asec.Push("app_name    = OneLocale_Demo")
    asec.Push("description = OneLocale Test & Demo für AHKv2")
    asec.Push("translator  = Google")
    asec.Push("date        =")
    asec.Push("comment     =")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["app_name"] := "OneLocale_Demo"
    msec["comment"] := ""
    msec["date"] := ""
    msec["description"] := "OneLocale Test & Demo für AHKv2"
    msec["lang_id"] := "de"
    msec["lang_name"] := "German"
    msec["translator"] := "Google"
    msec["version"] := "1.4"


    ; section 'dialog_browse'
    msec := Map()
    msec[":map_name:"] := "dialog_browse"
    mlng["dialog_browse"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title  = Select a text file")
    asec.Push("filter = Text Files \z (*.txt, *.ahk)")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["filter"] := "Text Files \z (*.txt, *.ahk)"
    msec["title"] := "Select a text file"


    ; section 'errors'
    msec := Map()
    msec[":map_name:"] := "errors"
    mlng["errors"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("bad_path                         = Die Datei \n'%path%' \n konnte nicht gefunden werden.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["bad_path"] := "Die Datei \n'%path%' \n konnte nicht gefunden werden."


    ; section 'gui'
    msec := Map()
    msec[":map_name:"] := "gui"
    mlng["gui"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title       = %title% - Ausführung %ver% \z\\ any text after '\z' is a comment to the translator.")
    asec.Push("ctlText1    = Geben Sie das heutige Datum ein:")
    asec.Push("ctlChk1     = &Möglichkeit 1")
    asec.Push("btn_Error   = &Test")
    asec.Push("btn_Help    = &Helfen")
    asec.Push("btn_Browse  = &Browse…")
    asec.Push("btn_Quit    = Ausfahrt")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Browse"] := "&Browse…"
    msec["btn_Error"] := "&Test"
    msec["btn_Help"] := "&Helfen"
    msec["btn_Quit"] := "Ausfahrt"
    msec["ctlChk1"] := "&Möglichkeit 1"
    msec["ctlText1"] := "Geben Sie das heutige Datum ein:"
    msec["title"] := "%title% - Ausführung %ver% \z\\ any text after '\z' is a comment to the translator."


    ; section 'list'
    msec := Map()
    msec[":map_name:"] := "list"
    mlng["list"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("Red         = Rot")
    asec.Push("Green       = Grün")
    asec.Push("Blue        = Blau")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["Blue"] := "Blau"
    msec["Green"] := "Grün"
    msec["Red"] := "Rot"


    ; section 'menu'
    msec := Map()
    msec[":map_name:"] := "menu"
    mlng["menu"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("language    = &Sprache...\tCtrl+S")
    asec.Push("file_test   = &Fehlermeldung generieren\tCtrl+F")
    asec.Push("file_quit   = &Beenden\tCtrl+B")
    asec.Push("help_read   = &Readme im Browser anzeigen...\tF1")
    asec.Push("mnu_file    = &Datei")
    asec.Push("mnu_help    = &Helfen")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["file_quit"] := "&Beenden\tCtrl+B"
    msec["file_test"] := "&Fehlermeldung generieren\tCtrl+F"
    msec["help_read"] := "&Readme im Browser anzeigen...\tF1"
    msec["language"] := "&Sprache...\tCtrl+S"
    msec["mnu_file"] := "&Datei"
    msec["mnu_help"] := "&Helfen"


    ; section 'multiline'
    msec := Map()
    msec[":map_name:"] := "multiline"
    mlng["multiline"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("→ Mehrzeiliger Text:")
    asec.Push("“Wer mit Ungeheuern kämpft, mag zusehn,")
    asec.Push("dass er nicht dabei zum Ungeheuer wird.")
    asec.Push("Und wenn du lange in einen Abgrund blickst,")
    asec.Push("blickt der Abgrund auch in dich hinein.” \n—Nietzsche")
    msec["[section]"] := asec

    ; ...section keys and values


    ; section 'tooltips'
    msec := Map()
    msec[":map_name:"] := "tooltips"
    mlng["tooltips"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("ctlEdit1    = Hier noch etwas Hilfe zu diesem Eintrag.")
    asec.Push("ctlList1    = Wählen Sie eine Farbe aus der Liste.")
    asec.Push("ctlChk1     = Diese Option bewirkt nichts.")
    asec.Push("btn_Error   = Erstellen Sie eine gefälschte Fehlermeldung")
    asec.Push("btn_Help    = Lese die readme Datei.")
    asec.Push("multiline   = Mehrzeiliger Test.")
    asec.Push("btn_Browse  = Browse for a file.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Browse"] := "Browse for a file."
    msec["btn_Error"] := "Erstellen Sie eine gefälschte Fehlermeldung"
    msec["btn_Help"] := "Lese die readme Datei."
    msec["ctlChk1"] := "Diese Option bewirkt nichts."
    msec["ctlEdit1"] := "Hier noch etwas Hilfe zu diesem Eintrag."
    msec["ctlList1"] := "Wählen Sie eine Farbe aus der Liste."
    msec["multiline"] := "Mehrzeiliger Test."


    ;==========================
    ; submap '1'
    ; source = E:\Programs\AHK_root\AHKv2A\OneLocale\utilities\OneLocale_Demo\lang_load\..\..\..\lib\OneLocale_Dialog-template.lang

    msub := Map()
    msub[":map_name:"] := "1"
    mlng[":extenders:"]["[section]"].Push(msub)

    ; section 'dialog_lang'
    msec := Map()
    msec[":map_name:"] := "dialog_lang"
    msub["dialog_lang"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title       = Change Language")
    asec.Push("lbl_lang    = User Interface Language:")
    asec.Push("lbl_buttons = App will restart if you change Language\n(work in progress will be lost)")
    asec.Push("btn_OK      = OK")
    asec.Push("btn_Cancel  = Cancel")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Cancel"] := "Cancel"
    msec["btn_OK"] := "OK"
    msec["lbl_buttons"] := "App will restart if you change Language\n(work in progress will be lost)"
    msec["lbl_lang"] := "User Interface Language:"
    msec["title"] := "Change Language"


    ; section 'errors'
    msec := Map()
    msec[":map_name:"] := "errors"
    msub["errors"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("OneLocaleDlg_ini_write_error    = Could not write to configuration file\n %path%")
    asec.Push("OneLocaleDlg_lang_not_found     = 'Language' entry in .INI file \n '%ini_path%' \n not found")
    asec.Push("OneLocaleDlg_newname_not_found  = Unexpected error: Language file not found for '%newname%'.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["OneLocaleDlg_ini_write_error"] := "Could not write to configuration file\n %path%"
    msec["OneLocaleDlg_lang_not_found"] := "'Language' entry in .INI file \n '%ini_path%' \n not found"
    msec["OneLocaleDlg_newname_not_found"] := "Unexpected error: Language file not found for '%newname%'."


    ; section 'general'
    msec := Map()
    msec[":map_name:"] := "general"
    msub["general"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("lang_id     = en")
    asec.Push("lang_name   = English")
    asec.Push("app_name    =")
    asec.Push("description =")
    asec.Push("translator  =")
    asec.Push("date        =")
    asec.Push("comment     =")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["app_name"] := ""
    msec["comment"] := ""
    msec["date"] := ""
    msec["description"] := ""
    msec["lang_id"] := "en"
    msec["lang_name"] := "English"
    msec["translator"] := ""


    ; section 'tooltips_dialog_lang'
    msec := Map()
    msec[":map_name:"] := "tooltips_dialog_lang"
    msub["tooltips_dialog_lang"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("lang_list = Set User Interface Language")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["lang_list"] := "Set User Interface Language"

    return
}
; (end)

