#Requires AutoHotkey v2.0

; AUTO-GENERATED - DO NOT EDIT
; timestamp 20251210170437
; generated by OneLocale_Baker.ahk :: BakeLangMap()
; source = E:\Programs\AHK_root\AHKv2A\OneLocale\utilities\OneLocale_Demo\lang_load\OneLocale_Demo-[en].lang

OneLocale_BuildMap_en()

/*****************************************
 * ##### OneLocale_BuildMap_en: initialize global Map 'g_lang_map'
 * - Conversion of a .LANG file into a Map tree
 */
OneLocale_BuildMap_en()
{
    global g_lang_map
    if (!IsObject(g_lang_map))
        g_lang_map := Map()

    local mlng, msec, msub, asec
    mlng := Map()
    mlng[":lang_id:"] := "en"
    g_lang_map["en"] := mlng


    ; section ':extenders:'
    msec := Map()
    msec[":map_name:"] := ":extenders:"
    mlng[":extenders:"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("..\..\..\lib\OneLocale_Dialog-template.lang")
    asec.Push("..\..\..\lib\Versions-template.lang")
    msec["[section]"] := asec

    ; ...section keys and values


    ; section 'General'
    msec := Map()
    msec[":map_name:"] := "General"
    mlng["General"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("version     = 1.4")
    asec.Push("lang_id     = en")
    asec.Push("lang_name   = English")
    asec.Push("app_name    = OneLocale_Demo")
    asec.Push("description = OneLocale test & demo for AHKv2")
    asec.Push("translator  =")
    asec.Push("date        =")
    asec.Push("comment     =")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["app_name"] := "OneLocale_Demo"
    msec["comment"] := ""
    msec["date"] := ""
    msec["description"] := "OneLocale test & demo for AHKv2"
    msec["lang_id"] := "en"
    msec["lang_name"] := "English"
    msec["translator"] := ""
    msec["version"] := "1.4"


    ; section 'dialog_browse'
    msec := Map()
    msec[":map_name:"] := "dialog_browse"
    mlng["dialog_browse"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title  = Select a text file")
    asec.Push("filter = Text Files \z (*.txt, *.ahk)")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["filter"] := "Text Files \z (*.txt, *.ahk)"
    msec["title"] := "Select a text file"


    ; section 'errors'
    msec := Map()
    msec[":map_name:"] := "errors"
    mlng["errors"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("bad_path                         = The file \n'%path%' \n could not be found.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["bad_path"] := "The file \n'%path%' \n could not be found."


    ; section 'gui'
    msec := Map()
    msec[":map_name:"] := "gui"
    mlng["gui"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title       = %title% - version %ver% \z note, any text after '\z' is a comment to the translator.")
    asec.Push("ctlText1    = Enter today's date:")
    asec.Push("ctlChk1     = &Option 1")
    asec.Push("btn_Error   = &Test")
    asec.Push("btn_Help    = &Help")
    asec.Push("btn_Browse  = &Browse…")
    asec.Push("btn_Quit    = Quit")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Browse"] := "&Browse…"
    msec["btn_Error"] := "&Test"
    msec["btn_Help"] := "&Help"
    msec["btn_Quit"] := "Quit"
    msec["ctlChk1"] := "&Option 1"
    msec["ctlText1"] := "Enter today's date:"
    msec["title"] := "%title% - version %ver% \z note, any text after '\z' is a comment to the translator."


    ; section 'list'
    msec := Map()
    msec[":map_name:"] := "list"
    mlng["list"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("Red         = Red")
    asec.Push("Green       = Green")
    asec.Push("Blue        = Blue")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["Blue"] := "Blue"
    msec["Green"] := "Green"
    msec["Red"] := "Red"


    ; section 'menu'
    msec := Map()
    msec[":map_name:"] := "menu"
    mlng["menu"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("language    = &Language... \t Ctrl+L")
    asec.Push("file_test   = &Generate error message \t Ctrl+E")
    asec.Push("file_quit   = &Quit \t Ctrl+Q")
    asec.Push("help_read   = &View Readme in browser... \t F1")
    asec.Push("mnu_file    = &File")
    asec.Push("mnu_help    = &Help")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["file_quit"] := "&Quit \t Ctrl+Q"
    msec["file_test"] := "&Generate error message \t Ctrl+E"
    msec["help_read"] := "&View Readme in browser... \t F1"
    msec["language"] := "&Language... \t Ctrl+L"
    msec["mnu_file"] := "&File"
    msec["mnu_help"] := "&Help"


    ; section 'multiline'
    msec := Map()
    msec[":map_name:"] := "multiline"
    mlng["multiline"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("→ Multiline text:")
    asec.Push("“Whoever battles monsters should see to it that")
    asec.Push("in the process he does not become a monster himself.")
    asec.Push("And when you look long into the abyss,")
    asec.Push("the abyss also looks into you.” \n—Nietzsche")
    msec["[section]"] := asec

    ; ...section keys and values


    ; section 'tooltips'
    msec := Map()
    msec[":map_name:"] := "tooltips"
    mlng["tooltips"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("ctlEdit1    = Here is a little more help on this entry.")
    asec.Push("ctlList1    = Choose a color from the list.")
    asec.Push("ctlChk1     = This option does nothing.")
    asec.Push("btn_Error   = Create a fake error message")
    asec.Push("btn_Help    = View the Readme file.")
    asec.Push("multiline   = Multiline test.")
    asec.Push("btn_Browse  = Browse for a file.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Browse"] := "Browse for a file."
    msec["btn_Error"] := "Create a fake error message"
    msec["btn_Help"] := "View the Readme file."
    msec["ctlChk1"] := "This option does nothing."
    msec["ctlEdit1"] := "Here is a little more help on this entry."
    msec["ctlList1"] := "Choose a color from the list."
    msec["multiline"] := "Multiline test."


    ;==========================
    ; submap '1'
    ; source = E:\Programs\AHK_root\AHKv2A\OneLocale\utilities\OneLocale_Demo\lang_load\..\..\..\lib\OneLocale_Dialog-template.lang

    msub := Map()
    msub[":map_name:"] := "1"
    mlng[":extenders:"]["[section]"].Push(msub)

    ; section 'dialog_lang'
    msec := Map()
    msec[":map_name:"] := "dialog_lang"
    msub["dialog_lang"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("title       = Change Language")
    asec.Push("lbl_lang    = User Interface Language:")
    asec.Push("lbl_buttons = App will restart if you change Language\n(work in progress will be lost)")
    asec.Push("btn_OK      = OK")
    asec.Push("btn_Cancel  = Cancel")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["btn_Cancel"] := "Cancel"
    msec["btn_OK"] := "OK"
    msec["lbl_buttons"] := "App will restart if you change Language\n(work in progress will be lost)"
    msec["lbl_lang"] := "User Interface Language:"
    msec["title"] := "Change Language"


    ; section 'errors'
    msec := Map()
    msec[":map_name:"] := "errors"
    msub["errors"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("OneLocaleDlg_ini_write_error    = Could not write to configuration file\n %path%")
    asec.Push("OneLocaleDlg_lang_not_found     = 'Language' entry in .INI file \n '%ini_path%' \n not found")
    asec.Push("OneLocaleDlg_newname_not_found  = Unexpected error: Language file not found for '%newname%'.")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["OneLocaleDlg_ini_write_error"] := "Could not write to configuration file\n %path%"
    msec["OneLocaleDlg_lang_not_found"] := "'Language' entry in .INI file \n '%ini_path%' \n not found"
    msec["OneLocaleDlg_newname_not_found"] := "Unexpected error: Language file not found for '%newname%'."


    ; section 'general'
    msec := Map()
    msec[":map_name:"] := "general"
    msub["general"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("lang_id     = en")
    asec.Push("lang_name   = English")
    asec.Push("app_name    =")
    asec.Push("description =")
    asec.Push("translator  =")
    asec.Push("date        =")
    asec.Push("comment     =")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["app_name"] := ""
    msec["comment"] := ""
    msec["date"] := ""
    msec["description"] := ""
    msec["lang_id"] := "en"
    msec["lang_name"] := "English"
    msec["translator"] := ""


    ; section 'tooltips_dialog_lang'
    msec := Map()
    msec[":map_name:"] := "tooltips_dialog_lang"
    msub["tooltips_dialog_lang"] := msec

    ; ...[section] raw data
    asec := []
    asec.Push("lang_list = Set User Interface Language")
    msec["[section]"] := asec

    ; ...section keys and values
    msec["lang_list"] := "Set User Interface Language"

    return
}
; (end)

